title: Search Management Map
lang: en
description: Search Management Map is a tool for managing search and rescue operations. The primary interface is a leaflet GIS map.
baseurl: "/search-management-map" # the subpath of your site, e.g. /blog
url: "https://canterbury-air-patrol.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  canterbury-air-patrol

# Build settings
remote_theme: rundocs/jekyll-rtd-theme

nav_version: true

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
