version: '3'

services:
  db:
    image: mdillon/postgis
    healthcheck:
      test: "pg_isready --username=postgres"
      timeout: 10s
      retries: 20
  app:
    build: .
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASS=password
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=administrator
      - DJANGO_SUPERUSER_EMAIL=me@example.com
  web:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./static/:/static/
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
