version: '3'

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: "pg_isready --username=postgres"
      timeout: 10s
      retries: 20
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASS=password
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=administrator
      - DJANGO_SUPERUSER_EMAIL=me@example.com
