# Generated by Django 6.0.5 on 2026-05-24 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0100_squashed_2025_03"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["user", "removed"], name="organizatio_user_id_0478ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["organization", "user", "removed"],
                name="organizatio_organiz_114d55_idx",
            ),
        ),
    ]
