# Generated by Django 3.2.10 on 2021-12-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapTileLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('base', models.BooleanField(default=False)),
                ('attribution', models.TextField(blank=True, null=True)),
                ('minZoom', models.IntegerField(default=0)),
                ('maxZoom', models.IntegerField(default=16)),
                ('subdomains', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('relativeOrder', models.IntegerField()),
            ],
        ),
    ]
