# Generated by Django 2.2.6 on 2019-10-11 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('add', 'Added/Created an Object'), ('del', 'Removed an Object'), ('upd', 'Updated/Edited an Object'), ('sbg', 'Asset Started Search'), ('snd', 'Asset Finished Search'), ('usr', 'User defined Event')], max_length=3)),
                ('message', models.TextField()),
                ('url', models.TextField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mission.Mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creatortimeline_timelineentry_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
