# Generated by Django 3.0.6 on 2020-05-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20191230_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='event_type',
            field=models.CharField(choices=[('add', 'Added/Created an Object'), ('del', 'Removed an Object'), ('upd', 'Updated/Edited an Object'), ('sbg', 'Asset Started Search'), ('snd', 'Asset Finished Search'), ('usr', 'User defined Event'), ('uad', 'User added to mission'), ('uup', 'User updated'), ('aad', 'Asset added to mission'), ('arm', 'Asset removed from mission'), ('ipc', 'Image priority changed'), ('que', 'Search was Queued or Dequeued')], max_length=3),
        ),
    ]
