# Generated by Django 4.0.1 on 2022-01-19 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0005_auto_20200520_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
