# Generated by Django 5.1.6 on 2025-03-03 08:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("timeline", "0001_initial"),
        ("timeline", "0002_auto_20191012_1337"),
        ("timeline", "0003_auto_20191012_1444"),
        ("timeline", "0004_auto_20191230_1233"),
        ("timeline", "0005_auto_20200520_2253"),
        ("timeline", "0006_alter_timelineentry_user"),
        ("timeline", "0007_alter_timelineentry_event_type"),
        ("timeline", "0008_alter_timelineentry_event_type"),
        ("timeline", "0009_alter_timelineentry_event_type"),
        ("timeline", "0010_alter_timelineentry_event_type"),
    ]

    initial = True

    dependencies = [
        ("mission", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeLineEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("add", "Added/Created an Object"),
                            ("del", "Removed an Object"),
                            ("upd", "Updated/Edited an Object"),
                            ("sbg", "Asset Started Search"),
                            ("snd", "Asset Finished Search"),
                            ("usr", "User defined Event"),
                            ("oad", "Organization added to mission"),
                            ("oup", "Organization updated"),
                            ("orm", "Organization removed from mission"),
                            ("uad", "User added to mission"),
                            ("uup", "User updated"),
                            ("aad", "Asset added to mission"),
                            ("arm", "Asset removed from mission"),
                            ("ipc", "Image priority changed"),
                            ("que", "Search was Queued or Dequeued"),
                            ("mas", "Mission Asset Status"),
                            ("acs", "Asset Command Sent"),
                            ("acr", "Asset Command Response"),
                            ("xra", "External Reference Add"),
                            ("xrc", "External Reference Change"),
                            ("xrr", "External Reference Remove"),
                        ],
                        max_length=3,
                    ),
                ),
                ("message", models.TextField()),
                ("url", models.TextField(blank=True, null=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mission.mission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator%(app_label)s_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
