# Generated by Django 5.1.6 on 2026-06-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0100_squashed_2025_03"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineentry",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("add", "Added/Created an Object"),
                    ("del", "Removed an Object"),
                    ("upd", "Updated/Edited an Object"),
                    ("sbg", "Asset Started Search"),
                    ("snd", "Asset Finished Search"),
                    ("usr", "User defined Event"),
                    ("oad", "Organization added to mission"),
                    ("oup", "Organization updated"),
                    ("orm", "Organization removed from mission"),
                    ("uad", "User added to mission"),
                    ("uup", "User updated"),
                    ("aad", "Asset added to mission"),
                    ("arm", "Asset removed from mission"),
                    ("ipc", "Image priority changed"),
                    ("que", "Search was Queued"),
                    ("unq", "Search was Unqueued"),
                    ("mas", "Mission Asset Status"),
                    ("acs", "Asset Command Sent"),
                    ("acr", "Asset Command Response"),
                    ("xra", "External Reference Add"),
                    ("xrc", "External Reference Change"),
                    ("xrr", "External Reference Remove"),
                ],
                max_length=3,
            ),
        ),
    ]
