# Generated by Django 2.1.7 on 2019-03-27 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0004_linestringtimelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpointtime',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetpointtime',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deletordata_assetpointtime_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointtimelabel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointtimelabel',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deletordata_pointtimelabel_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetpointtime',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creatordata_assetpointtime_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointtimelabel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creatordata_pointtimelabel_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
