# Generated by Django 2.2 on 2019-04-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190428_0422'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='linestringtimelabel',
            index=models.Index(fields=['deleted', 'replaced_by'], name='data_linest_deleted_8e2577_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtimelabel',
            index=models.Index(fields=['deleted', 'replaced_by'], name='data_pointt_deleted_826250_idx'),
        ),
        migrations.AddIndex(
            model_name='polygontimelabel',
            index=models.Index(fields=['deleted', 'replaced_by'], name='data_polygo_deleted_ca4ece_idx'),
        ),
    ]
