# Generated by Django 2.2 on 2019-04-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20190428_0427'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assetpointtime',
            index=models.Index(fields=['asset', 'timestamp'], name='data_assetp_asset_i_a986b3_idx'),
        ),
    ]
