# Generated by Django 2.2.6 on 2019-10-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20191010_2226'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assetpointtime',
            name='data_assetp_asset_i_e48b42_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetpointtime',
            name='data_assetp_asset_i_a986b3_idx',
        ),
        migrations.AddIndex(
            model_name='assetpointtime',
            index=models.Index(fields=['mission', 'asset', '-timestamp'], name='data_assetp_mission_9f221a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetpointtime',
            index=models.Index(fields=['mission', 'asset', 'timestamp'], name='data_assetp_mission_e07c17_idx'),
        ),
    ]
