# Generated by Django 3.0.6 on 2020-05-23 05:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20200523_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineStringTimeLabel',
        ),
        migrations.DeleteModel(
            name='PointTimeLabel',
        ),
        migrations.DeleteModel(
            name='PolygonTimeLabel',
        ),
    ]
