# Generated by Django 3.0.6 on 2020-05-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20200523_1706'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='geotimelabel',
            name='data_geotim_mission_f8e195_idx',
        ),
        migrations.AddIndex(
            model_name='geotimelabel',
            index=models.Index(fields=['mission', 'deleted_at', 'replaced_at', 'created_at', 'geo_type'], name='data_geotim_mission_97b633_idx'),
        ),
        migrations.AddIndex(
            model_name='geotimelabel',
            index=models.Index(fields=['mission', 'deleted_at', 'replaced_at', 'geo_type'], name='data_geotim_mission_b38a2f_idx'),
        ),
    ]
