# Generated by Django 2.2 on 2019-04-25 02:16

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('command', models.CharField(choices=[('RTL', 'Return To Launch'), ('RON', 'Continue'), ('CIR', 'Circle'), ('GOTO', 'Goto position')], max_length=4)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('reason', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Asset')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
