# Generated by Django 3.0.8 on 2020-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetcommand_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcommand',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assetcommand',
            name='command',
            field=models.CharField(choices=[('RTL', 'Return To Launch'), ('RON', 'Continue'), ('CIR', 'Circle'), ('GOTO', 'Goto position'), ('MC', 'Mission Complete'), ('AS', 'Abandon Search')], max_length=4),
        ),
    ]
