# Generated by Django 5.0.3 on 2024-04-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_auto_20200729_1017"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetStatusValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("inop", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
