# Generated by Django 5.0.3 on 2024-04-25 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_assetstatusvalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("since", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="assets.asset"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assetstatusvalue",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["asset"], name="assets_asse_asset_i_36262c_idx"
                    ),
                    models.Index(fields=["since"], name="assets_asse_since_fd5f07_idx"),
                ],
            },
        ),
    ]
