# Generated by Django 5.0.6 on 2024-05-24 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_assetstatus"),
        ("icons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="icons.icon",
            ),
        ),
        migrations.AddField(
            model_name="assettype",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="icons.icon",
            ),
        ),
    ]
