# Generated by Django 5.1.6 on 2025-03-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0101_squashed_asset_command"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="AssetCommand",
                ),
            ],
            # This table is going to be reused in Mission
            database_operations=[
                migrations.AlterModelTable(
                    name='AssetCommand',
                    table='mission_assetcommand',
                ),
            ],
        ),
    ]
