# Generated by Django 6.0.5 on 2026-05-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_delete_assetcommand"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assetstatus",
            name="assets_asse_asset_i_36262c_idx",
        ),
        migrations.RemoveIndex(
            model_name="assetstatus",
            name="assets_asse_since_fd5f07_idx",
        ),
        migrations.AddIndex(
            model_name="assetstatus",
            index=models.Index(
                fields=["asset", "-since"], name="assets_asse_asset_i_abd38a_idx"
            ),
        ),
    ]
