# Generated by Django 5.1.6 on 2025-03-18 09:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("assets", "0002_assetcommand"),
        ("assets", "0003_assetcommand_mission"),
        ("assets", "0004_auto_20200729_1017"),
        ("assets", "0008_remove_assetcommand_acknowledged_and_more"),
    ]

    dependencies = [
        ("assets", "0100_squashed_2025_03"),
        ("mission", "0100_squashed_2025_03"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCommand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "command",
                    models.CharField(
                        choices=[
                            ("RTL", "Return To Launch"),
                            ("RON", "Continue"),
                            ("CIR", "Circle"),
                            ("GOTO", "Goto position"),
                            ("MC", "Mission Complete"),
                            ("AS", "Abandon Search"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="assets.asset"
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_by%(app_label)s_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mission.mission",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responder%(app_label)s_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "response_message",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "response_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
    ]
