"""
Django settings for smm project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Import other settings
from smm.local_settings import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

with open(os.path.join(BASE_DIR, 'smm', 'secretkey.txt')) as f:
    SECRET_KEY = f.read().strip()

# Application definition

INSTALLED_APPS = [
    'mission',
    'map',
    'assets',
    'data',
    'search',
    'timeline',
    'images',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'leaflet',
    'bootstrap4',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smm.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

LOGIN_REDIRECT_URL = '/'

LEAFLET_CONFIG['PLUGINS'] = {
    'realtime': {
        'js': 'leaflet/realtime/leaflet-realtime.js',
        'auto-include': True,
    },
    'Dialog': {
        'js': 'leaflet/dialog/Leaflet.Dialog.js',
        'css': 'leaflet/dialog/Leaflet.Dialog.css',
        'auto-include': True,
    },
    'POIAdder': {
        'js': 'POIAdder/POIAdder.js',
        'css': 'POIAdder/POIAdder.css',
        'auto-include': True,
    },
    'PolygonAdder': {
        'js': 'PolygonAdder/PolygonAdder.js',
        'css': 'PolygonAdder/PolygonAdder.css',
        'auto-include': True,
    },
    'LineAdder': {
        'js': 'LineAdder/LineAdder.js',
        'css': 'LineAdder/LineAdder.css',
        'auto-include': True,
    },
    'SearchAdder': {
        'js': 'SearchAdder/SearchAdder.js',
        'auto-include': True,
    },
    'SMMAdmin': {
        'js': 'Admin/admin.js',
        'auto-include': True,
    },
    'ImageUploader': {
        'js': 'ImageUploader/ImageUploader.js',
        'auto-include': True,
    },
    'LocateControl': {
        'js': 'leaflet/locatecontrol/L.Control.Locate.min.js',
        'css': ['leaflet/locatecontrol/L.Control.Locate.mapbox.min.css', 'leaflet/locatecontrol/L.Control.Locate.min.css'],
        'auto-include': True,
    },
}
