# Generated by Django 3.2.4 on 2021-06-27 12:01

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0019_auto_20200523_1816'),
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarineTotalDriftVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326)),
                ('alt', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('leeway_multiplier', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('leeway_modifier', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bymarinesar_marinetotaldriftvector_related', to=settings.AUTH_USER_MODEL)),
                ('datum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.geotimelabel')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deletormarinesar_marinetotaldriftvector_related', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mission.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarineTotalDriftVectorWind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('wind_from_direction', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)])),
                ('wind_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_drift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marinesar.marinetotaldriftvector')),
            ],
        ),
        migrations.CreateModel(
            name='MarineTotalDriftVectorCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('direction', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)])),
                ('speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_drift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marinesar.marinetotaldriftvector')),
            ],
        ),
        migrations.AddIndex(
            model_name='marinetotaldriftvectorwind',
            index=models.Index(fields=['total_drift', 'order'], name='marinesar_m_total_d_6456e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marinetotaldriftvectorwind',
            unique_together={('total_drift', 'order')},
        ),
        migrations.AddIndex(
            model_name='marinetotaldriftvectorcurrent',
            index=models.Index(fields=['total_drift', 'order'], name='marinesar_m_total_d_c74fa2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marinetotaldriftvectorcurrent',
            unique_together={('total_drift', 'order')},
        ),
        migrations.AddIndex(
            model_name='marinetotaldriftvector',
            index=models.Index(fields=['mission', 'deleted_at', 'replaced_at', 'created_at'], name='marinesar_m_mission_34931b_idx'),
        ),
    ]
