# Generated by Django 5.1.6 on 2025-03-18 10:48

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("marinesar", "0001_initial"),
        ("marinesar", "0002_alter_marinetotaldriftvector_created_by_and_more"),
    ]

    initial = True

    dependencies = [
        ("data", "0019_auto_20200523_1816"),
        ("mission", "0100_squashed_2025_03"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarineTotalDriftVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geo",
                    django.contrib.gis.db.models.fields.GeometryField(
                        geography=True, srid=4326
                    ),
                ),
                ("alt", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("replaced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "leeway_multiplier",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "leeway_modifier",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_bymarinesar_marinetotaldriftvector_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "datum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.geotimelabel",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deletormarinesar_marinetotaldriftvector_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mission.mission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarineTotalDriftVectorWind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "wind_from_direction",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(359),
                        ]
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "total_drift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="marinesar.marinetotaldriftvector",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["total_drift", "order"],
                        name="marinesar_m_total_d_6456e3_idx",
                    )
                ],
                "unique_together": {("total_drift", "order")},
            },
        ),
        migrations.CreateModel(
            name="MarineTotalDriftVectorCurrent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "direction",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(359),
                        ]
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "total_drift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="marinesar.marinetotaldriftvector",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["total_drift", "order"],
                        name="marinesar_m_total_d_c74fa2_idx",
                    )
                ],
                "unique_together": {("total_drift", "order")},
            },
        ),
        migrations.AddIndex(
            model_name="marinetotaldriftvector",
            index=models.Index(
                fields=["mission", "deleted_at", "replaced_at", "created_at"],
                name="marinesar_m_mission_34931b_idx",
            ),
        ),
        migrations.AlterField(
            model_name="marinetotaldriftvector",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by%(app_label)s_%(class)s_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="marinetotaldriftvector",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deletor%(app_label)s_%(class)s_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
