# Generated by Django 4.0.5 on 2022-07-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_alter_mission_closed_by_alter_mission_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='mission_name',
            new_name='mission_description',
        ),
    ]
