# Generated by Django 4.0.5 on 2022-07-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_rename_mission_name_mission_mission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
