# Generated by Django 5.1.3 on 2024-11-28 07:10
# Expanded to automatically migrate all the admins

from django.db import migrations, models


def forward_func(apps, schema_editor):
    MissionUsers = apps.get_model('mission', 'missionuser')
    for user in MissionUsers.objects.all():
        # Set the permissions_admin field based on role field
        user.permissions_admin = user.role == 'A'
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("mission", "0006_missionassetstatusvalue_missionassetstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionuser",
            name="permissions_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forward_func),
        migrations.RemoveField(
            model_name="missionuser",
            name="role",
        ),
    ]
