# Generated by Django 5.1.3 on 2024-11-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission", "0007_remove_missionuser_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionuser",
            name="permissions_organization_add",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="missionuser",
            name="permissions_user_add",
            field=models.BooleanField(default=False),
        ),
    ]
