# Generated by Django 5.1.3 on 2024-11-30 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mission", "0008_missionuser_permissions_organization_add_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missionorganization",
            name="role",
        ),
    ]
