# Generated by Django 5.1.3 on 2024-11-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission", "0009_remove_missionorganization_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionorganization",
            name="permissions_organization_add",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="missionorganization",
            name="permissions_user_add",
            field=models.BooleanField(default=False),
        ),
    ]
