# Generated by Django 6.0.5 on 2026-05-24 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_remove_assetstatus_assets_asse_asset_i_36262c_idx_and_more"),
        ("mission", "0012_assetcommand"),
        (
            "organization",
            "2026_organizationmember_organizatio_user_id_0478ff_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="missionassetstatus",
            name="mission_mis_mission_da6947_idx",
        ),
        migrations.RemoveIndex(
            model_name="missionassetstatus",
            name="mission_mis_since_1dcbf5_idx",
        ),
        migrations.AddIndex(
            model_name="missionasset",
            index=models.Index(
                fields=["mission", "asset", "removed"],
                name="mission_mis_mission_4ebf49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missionassetstatus",
            index=models.Index(
                fields=["mission_asset", "-since"],
                name="mission_mis_mission_cc7f29_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missionorganization",
            index=models.Index(
                fields=["mission", "organization", "removed"],
                name="mission_mis_mission_3628e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missionuser",
            index=models.Index(
                fields=["mission", "user"], name="mission_mis_mission_ea03cc_idx"
            ),
        ),
    ]
