# Generated by Django 2.1.7 on 2019-03-31 04:41

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0006_auto_20190328_1035'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('sweep_width', models.IntegerField()),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.Asset')),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.AssetType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('datum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.PointTimeLabel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
