# Generated by Django 2.2 on 2019-04-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('search', '0004_tracklinecreepingsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandingboxsearch',
            name='inprogress_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inprogress_bysearch_expandingboxsearch_related', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='sectorsearch',
            name='inprogress_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inprogress_bysearch_sectorsearch_related', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='tracklinecreepingsearch',
            name='inprogress_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inprogress_bysearch_tracklinecreepingsearch_related', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='tracklinesearch',
            name='inprogress_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inprogress_bysearch_tracklinesearch_related', to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='expandingboxsearch',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_bysearch_expandingboxsearch_related', to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='sectorsearch',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_bysearch_sectorsearch_related', to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='tracklinecreepingsearch',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_bysearch_tracklinecreepingsearch_related', to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='tracklinesearch',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_bysearch_tracklinesearch_related', to='assets.Asset'),
        ),
    ]
