# Generated by Django 2.2 on 2019-04-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190407_1051'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expandingboxsearch',
            index=models.Index(fields=['created_for'], name='search_expa_created_e5c35d_idx'),
        ),
        migrations.AddIndex(
            model_name='expandingboxsearch',
            index=models.Index(fields=['inprogress_by'], name='search_expa_inprogr_8a4fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='expandingboxsearch',
            index=models.Index(fields=['completed'], name='search_expa_complet_375b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorsearch',
            index=models.Index(fields=['created_for'], name='search_sect_created_03cdb4_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorsearch',
            index=models.Index(fields=['inprogress_by'], name='search_sect_inprogr_64e49d_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorsearch',
            index=models.Index(fields=['completed'], name='search_sect_complet_66b82f_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinecreepingsearch',
            index=models.Index(fields=['created_for'], name='search_trac_created_f6c6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinecreepingsearch',
            index=models.Index(fields=['inprogress_by'], name='search_trac_inprogr_68a38f_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinecreepingsearch',
            index=models.Index(fields=['completed'], name='search_trac_complet_548169_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinesearch',
            index=models.Index(fields=['created_for'], name='search_trac_created_d09889_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinesearch',
            index=models.Index(fields=['inprogress_by'], name='search_trac_inprogr_5e4765_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinesearch',
            index=models.Index(fields=['completed'], name='search_trac_complet_8c7680_idx'),
        ),
    ]
