# Generated by Django 2.2.1 on 2019-05-26 03:28

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20190428_0514'),
        ('assets', '0002_assetcommand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0006_auto_20190428_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('sweep_width', models.IntegerField()),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_bysearch_polygonsearch_related', to='assets.Asset')),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.AssetType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('datum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.PolygonTimeLabel')),
                ('inprogress_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inprogress_bysearch_polygonsearch_related', to='assets.Asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='polygonsearch',
            index=models.Index(fields=['created_for'], name='search_poly_created_ae79e2_idx'),
        ),
        migrations.AddIndex(
            model_name='polygonsearch',
            index=models.Index(fields=['inprogress_by'], name='search_poly_inprogr_f9d901_idx'),
        ),
        migrations.AddIndex(
            model_name='polygonsearch',
            index=models.Index(fields=['completed'], name='search_poly_complet_28b10e_idx'),
        ),
    ]
