# Generated by Django 2.2.6 on 2019-10-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
        ('search', '0007_auto_20190526_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandingboxsearch',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mission.Mission'),
        ),
        migrations.AddField(
            model_name='polygonsearch',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mission.Mission'),
        ),
        migrations.AddField(
            model_name='sectorsearch',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mission.Mission'),
        ),
        migrations.AddField(
            model_name='tracklinecreepingsearch',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mission.Mission'),
        ),
        migrations.AddField(
            model_name='tracklinesearch',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mission.Mission'),
        ),
    ]
