# Generated by Django 2.2.6 on 2019-10-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20191010_2226'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expandingboxsearch',
            index=models.Index(fields=['mission'], name='search_expa_mission_bcdb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='polygonsearch',
            index=models.Index(fields=['mission'], name='search_poly_mission_7e0746_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorsearch',
            index=models.Index(fields=['mission'], name='search_sect_mission_76d1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinecreepingsearch',
            index=models.Index(fields=['mission'], name='search_trac_mission_92ab25_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinesearch',
            index=models.Index(fields=['mission'], name='search_trac_mission_0d86e7_idx'),
        ),
    ]
