# Generated by Django 3.0.6 on 2020-05-20 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetcommand_mission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission', '0001_initial'),
        ('search', '0009_auto_20191011_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueueEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_type', models.CharField(max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.Asset')),
                ('assettype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.AssetType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bysearch_searchqueueentry_related', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_bysearch_searchqueueentry_related', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mission.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='ExpandingBoxSearchQueueEntry',
            fields=[
                ('searchqueueentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.SearchQueueEntry')),
            ],
            bases=('search.searchqueueentry',),
        ),
        migrations.CreateModel(
            name='PolygonSearchQueueEntry',
            fields=[
                ('searchqueueentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.SearchQueueEntry')),
            ],
            bases=('search.searchqueueentry',),
        ),
        migrations.CreateModel(
            name='TrackLineSearchQueueEntry',
            fields=[
                ('searchqueueentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.SearchQueueEntry')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.TrackLineSearch')),
            ],
            bases=('search.searchqueueentry',),
        ),
        migrations.CreateModel(
            name='TrackLineCreepingSearchQueueEntry',
            fields=[
                ('searchqueueentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.SearchQueueEntry')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.TrackLineCreepingSearch')),
            ],
            bases=('search.searchqueueentry',),
        ),
        migrations.CreateModel(
            name='SectorSearchQueueEntry',
            fields=[
                ('searchqueueentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.SearchQueueEntry')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.SectorSearch')),
            ],
            bases=('search.searchqueueentry',),
        ),
        migrations.AddIndex(
            model_name='searchqueueentry',
            index=models.Index(fields=['mission'], name='search_sear_mission_1e1048_idx'),
        ),
        migrations.AddIndex(
            model_name='searchqueueentry',
            index=models.Index(fields=['created_at'], name='search_sear_created_d63b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchqueueentry',
            index=models.Index(fields=['deleted_at'], name='search_sear_deleted_61017a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchqueueentry',
            index=models.Index(fields=['asset'], name='search_sear_asset_i_bae2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='searchqueueentry',
            index=models.Index(fields=['assettype'], name='search_sear_assetty_6ce6a4_idx'),
        ),
        migrations.AddField(
            model_name='polygonsearchqueueentry',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.PolygonSearch'),
        ),
        migrations.AddField(
            model_name='expandingboxsearchqueueentry',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.ExpandingBoxSearch'),
        ),
    ]
