# Generated by Django 3.0.6 on 2020-05-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetcommand_mission'),
        ('search', '0010_auto_20200520_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expandingboxsearchqueueentry',
            name='search',
        ),
        migrations.RemoveField(
            model_name='expandingboxsearchqueueentry',
            name='searchqueueentry_ptr',
        ),
        migrations.RemoveField(
            model_name='polygonsearchqueueentry',
            name='search',
        ),
        migrations.RemoveField(
            model_name='polygonsearchqueueentry',
            name='searchqueueentry_ptr',
        ),
        migrations.RemoveField(
            model_name='searchqueueentry',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='searchqueueentry',
            name='assettype',
        ),
        migrations.RemoveField(
            model_name='searchqueueentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='searchqueueentry',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='searchqueueentry',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='sectorsearchqueueentry',
            name='search',
        ),
        migrations.RemoveField(
            model_name='sectorsearchqueueentry',
            name='searchqueueentry_ptr',
        ),
        migrations.RemoveField(
            model_name='tracklinecreepingsearchqueueentry',
            name='search',
        ),
        migrations.RemoveField(
            model_name='tracklinecreepingsearchqueueentry',
            name='searchqueueentry_ptr',
        ),
        migrations.RemoveField(
            model_name='tracklinesearchqueueentry',
            name='search',
        ),
        migrations.RemoveField(
            model_name='tracklinesearchqueueentry',
            name='searchqueueentry_ptr',
        ),
        migrations.AddField(
            model_name='expandingboxsearch',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expandingboxsearch',
            name='queued_for_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queued_for_assettypesearch_expandingboxsearch_related', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='expandingboxsearch',
            name='queued_for_assettype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queued_for_assettypesearch_expandingboxsearch_related', to='assets.AssetType'),
        ),
        migrations.AddField(
            model_name='polygonsearch',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polygonsearch',
            name='queued_for_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queued_for_assettypesearch_polygonsearch_related', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='polygonsearch',
            name='queued_for_assettype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queued_for_assettypesearch_polygonsearch_related', to='assets.AssetType'),
        ),
        migrations.AddField(
            model_name='sectorsearch',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectorsearch',
            name='queued_for_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queued_for_assettypesearch_sectorsearch_related', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='sectorsearch',
            name='queued_for_assettype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queued_for_assettypesearch_sectorsearch_related', to='assets.AssetType'),
        ),
        migrations.AddField(
            model_name='tracklinecreepingsearch',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracklinecreepingsearch',
            name='queued_for_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queued_for_assettypesearch_tracklinecreepingsearch_related', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='tracklinecreepingsearch',
            name='queued_for_assettype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queued_for_assettypesearch_tracklinecreepingsearch_related', to='assets.AssetType'),
        ),
        migrations.AddField(
            model_name='tracklinesearch',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracklinesearch',
            name='queued_for_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queued_for_assettypesearch_tracklinesearch_related', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='tracklinesearch',
            name='queued_for_assettype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queued_for_assettypesearch_tracklinesearch_related', to='assets.AssetType'),
        ),
        migrations.AddIndex(
            model_name='expandingboxsearch',
            index=models.Index(fields=['deleted', 'mission', 'inprogress_by', 'completed'], name='search_expa_deleted_61c18d_idx'),
        ),
        migrations.AddIndex(
            model_name='polygonsearch',
            index=models.Index(fields=['deleted', 'mission', 'inprogress_by', 'completed'], name='search_poly_deleted_7741f9_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorsearch',
            index=models.Index(fields=['deleted', 'mission', 'inprogress_by', 'completed'], name='search_sect_deleted_93cc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinecreepingsearch',
            index=models.Index(fields=['deleted', 'mission', 'inprogress_by', 'completed'], name='search_trac_deleted_fc74fa_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinesearch',
            index=models.Index(fields=['deleted', 'mission', 'inprogress_by', 'completed'], name='search_trac_deleted_302cee_idx'),
        ),
        migrations.DeleteModel(
            name='ExpandingBoxSearchQueueEntry',
        ),
        migrations.DeleteModel(
            name='PolygonSearchQueueEntry',
        ),
        migrations.DeleteModel(
            name='SearchQueueEntry',
        ),
        migrations.DeleteModel(
            name='SectorSearchQueueEntry',
        ),
        migrations.DeleteModel(
            name='TrackLineCreepingSearchQueueEntry',
        ),
        migrations.DeleteModel(
            name='TrackLineSearchQueueEntry',
        ),
    ]
