# Generated by Django 3.0.6 on 2020-05-23 04:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_migrate_polygontimelabel'),
        ('search', '0013_add_datum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expandingboxsearch',
            name='old_datum',
        ),
        migrations.RemoveField(
            model_name='polygonsearch',
            name='old_datum',
        ),
        migrations.RemoveField(
            model_name='sectorsearch',
            name='old_datum',
        ),
        migrations.RemoveField(
            model_name='tracklinecreepingsearch',
            name='old_datum',
        ),
        migrations.RemoveField(
            model_name='tracklinesearch',
            name='old_datum',
        ),
        migrations.AlterField(
            model_name='expandingboxsearch',
            name='datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.GeoTimeLabel'),
        ),
        migrations.AlterField(
            model_name='polygonsearch',
            name='datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.GeoTimeLabel'),
        ),
        migrations.AlterField(
            model_name='sectorsearch',
            name='datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.GeoTimeLabel'),
        ),
        migrations.AlterField(
            model_name='tracklinecreepingsearch',
            name='datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.GeoTimeLabel'),
        ),
        migrations.AlterField(
            model_name='tracklinesearch',
            name='datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.GeoTimeLabel'),
        ),
        migrations.AddIndex(
            model_name='expandingboxsearch',
            index=models.Index(fields=['deleted_at', 'mission', 'inprogress_by', 'completed'], name='search_expa_deleted_e33db8_idx'),
        ),
        migrations.AddIndex(
            model_name='polygonsearch',
            index=models.Index(fields=['deleted_at', 'mission', 'inprogress_by', 'completed'], name='search_poly_deleted_bc718a_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorsearch',
            index=models.Index(fields=['deleted_at', 'mission', 'inprogress_by', 'completed'], name='search_sect_deleted_e68757_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinecreepingsearch',
            index=models.Index(fields=['deleted_at', 'mission', 'inprogress_by', 'completed'], name='search_trac_deleted_a66ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklinesearch',
            index=models.Index(fields=['deleted_at', 'mission', 'inprogress_by', 'completed'], name='search_trac_deleted_205a8e_idx'),
        ),
    ]
