# Generated by Django 3.0.6 on 2020-05-23 05:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20200523_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expandingboxsearch',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='polygonsearch',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='sectorsearch',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='tracklinecreepingsearch',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='tracklinesearch',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326),
        ),
    ]
