# Generated by Django 3.0.6 on 2020-05-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_auto_20200523_2237'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='search',
            name='search_sear_mission_c76b3e_idx',
        ),
        migrations.RemoveField(
            model_name='search',
            name='queued_for_assettype',
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['mission', 'deleted_at', 'replaced_at', 'completed_at', 'inprogress_by', 'queued_for_asset', 'created_for'], name='search_sear_mission_ae703d_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['inprogress_by'], name='search_sear_inprogr_04e623_idx'),
        ),
    ]
