# Generated by Django 4.0.1 on 2022-01-19 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0004_auto_20200729_1017'),
        ('search', '0025_auto_20200523_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_by%(app_label)s_%(class)s_related', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='search',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deletor%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search',
            name='inprogress_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inprogress_by%(app_label)s_%(class)s_related', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='search',
            name='queued_for_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queued_for_assettype%(app_label)s_%(class)s_related', to='assets.asset'),
        ),
    ]
