# Generated by Django 4.1.3 on 2022-11-06 08:15

from django.db import migrations, models

def forward_func(apps, schema_editor):
    Search = apps.get_model('search', 'Search')
    TimeLineEntry = apps.get_model('timeline', 'TimeLineEntry')
    for search in Search.objects.all():
        if search.inprogress_by is not None:
            if search.inprogress_at is None:
                # Try finding the timeline entry
                tle = TimeLineEntry.objects.get(event_type='sbg', message__contains=f'({search.pk}):')
                if tle is not None:
                    search.inprogress_at = tle.timestamp
                else:
                    search.inprogress_at = search.completed_at
                search.save()


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0026_alter_search_completed_by_alter_search_created_by_and_more"),
        ('timeline', '0005_auto_20200520_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="inprogress_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(forward_func),
    ]
