# Generated by Django 6.0.6 on 2026-08-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_remove_assetstatus_assets_asse_asset_i_36262c_idx_and_more"),
        ("search", "0027_search_inprogress_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="abandoned_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="abandoned%(app_label)s_%(class)s_related",
                to="assets.asset",
            ),
        ),
    ]
