# Generated by Django 5.1.6 on 2025-03-03 08:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("search", "0001_initial"),
        ("search", "0002_expandingboxsearch"),
        ("search", "0003_tracklinesearch"),
        ("search", "0004_tracklinecreepingsearch"),
        ("search", "0005_auto_20190407_1051"),
        ("search", "0006_auto_20190428_0430"),
        ("search", "0007_auto_20190526_0328"),
        ("search", "0008_auto_20191010_2226"),
        ("search", "0009_auto_20191011_2141"),
        ("search", "0010_auto_20200520_2321"),
        ("search", "0011_auto_20200521_2225"),
        ("search", "0012_update_field_names"),
        ("search", "0013_add_datum"),
    ]

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("assets", "0002_assetcommand"),
        ("assets", "0003_assetcommand_mission"),
        ("data", "0006_auto_20190328_1035"),
        ("data", "0009_auto_20190428_0514"),
        ("data", "0013_geotimelabel"),
        ("mission", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpandingBoxSearch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line",
                    django.contrib.gis.db.models.fields.LineStringField(
                        geography=True, srid=4326
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted", models.BooleanField(default=False)),
                ("sweep_width", models.IntegerField()),
                ("completed", models.DateTimeField(blank=True, null=True)),
                ("iterations", models.IntegerField()),
                ("first_bearing", models.IntegerField()),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_bysearch_expandingboxsearch_related",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assettype",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "datum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.pointtimelabel",
                    ),
                ),
                (
                    "inprogress_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inprogress_bysearch_expandingboxsearch_related",
                        to="assets.asset",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mission.mission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_for"], name="search_expa_created_e5c35d_idx"
                    ),
                    models.Index(
                        fields=["inprogress_by"], name="search_expa_inprogr_8a4fb0_idx"
                    ),
                    models.Index(
                        fields=["completed"], name="search_expa_complet_375b1c_idx"
                    ),
                    models.Index(
                        fields=["mission"], name="search_expa_mission_bcdb9f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PolygonSearch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line",
                    django.contrib.gis.db.models.fields.LineStringField(
                        geography=True, srid=4326
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted", models.BooleanField(default=False)),
                ("sweep_width", models.IntegerField()),
                ("completed", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_bysearch_polygonsearch_related",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assettype",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "datum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.polygontimelabel",
                    ),
                ),
                (
                    "inprogress_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inprogress_bysearch_polygonsearch_related",
                        to="assets.asset",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mission.mission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_for"], name="search_poly_created_ae79e2_idx"
                    ),
                    models.Index(
                        fields=["inprogress_by"], name="search_poly_inprogr_f9d901_idx"
                    ),
                    models.Index(
                        fields=["completed"], name="search_poly_complet_28b10e_idx"
                    ),
                    models.Index(
                        fields=["mission"], name="search_poly_mission_7e0746_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SectorSearch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line",
                    django.contrib.gis.db.models.fields.LineStringField(
                        geography=True, srid=4326
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted", models.BooleanField(default=False)),
                ("sweep_width", models.IntegerField()),
                ("completed", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_bysearch_sectorsearch_related",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assettype",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "datum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.pointtimelabel",
                    ),
                ),
                (
                    "inprogress_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inprogress_bysearch_sectorsearch_related",
                        to="assets.asset",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mission.mission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_for"], name="search_sect_created_03cdb4_idx"
                    ),
                    models.Index(
                        fields=["inprogress_by"], name="search_sect_inprogr_64e49d_idx"
                    ),
                    models.Index(
                        fields=["completed"], name="search_sect_complet_66b82f_idx"
                    ),
                    models.Index(
                        fields=["mission"], name="search_sect_mission_76d1f4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackLineCreepingSearch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line",
                    django.contrib.gis.db.models.fields.LineStringField(
                        geography=True, srid=4326
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted", models.BooleanField(default=False)),
                ("sweep_width", models.IntegerField()),
                ("completed", models.DateTimeField(blank=True, null=True)),
                ("width", models.IntegerField()),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_bysearch_tracklinecreepingsearch_related",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assettype",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "datum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.linestringtimelabel",
                    ),
                ),
                (
                    "inprogress_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inprogress_bysearch_tracklinecreepingsearch_related",
                        to="assets.asset",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mission.mission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_for"], name="search_trac_created_f6c6fc_idx"
                    ),
                    models.Index(
                        fields=["inprogress_by"], name="search_trac_inprogr_68a38f_idx"
                    ),
                    models.Index(
                        fields=["completed"], name="search_trac_complet_548169_idx"
                    ),
                    models.Index(
                        fields=["mission"], name="search_trac_mission_92ab25_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackLineSearch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line",
                    django.contrib.gis.db.models.fields.LineStringField(
                        geography=True, srid=4326
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted", models.BooleanField(default=False)),
                ("sweep_width", models.IntegerField()),
                ("completed", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_bysearch_tracklinesearch_related",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assettype",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "datum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.linestringtimelabel",
                    ),
                ),
                (
                    "inprogress_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inprogress_bysearch_tracklinesearch_related",
                        to="assets.asset",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mission.mission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_for"], name="search_trac_created_d09889_idx"
                    ),
                    models.Index(
                        fields=["inprogress_by"], name="search_trac_inprogr_5e4765_idx"
                    ),
                    models.Index(
                        fields=["completed"], name="search_trac_complet_8c7680_idx"
                    ),
                    models.Index(
                        fields=["mission"], name="search_trac_mission_0d86e7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchQueueEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("search_type", models.CharField(max_length=20)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.asset",
                    ),
                ),
                (
                    "assettype",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assettype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_bysearch_searchqueueentry_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deleted_bysearch_searchqueueentry_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mission.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpandingBoxSearchQueueEntry",
            fields=[
                (
                    "searchqueueentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.searchqueueentry",
                    ),
                ),
            ],
            bases=("search.searchqueueentry",),
        ),
        migrations.CreateModel(
            name="PolygonSearchQueueEntry",
            fields=[
                (
                    "searchqueueentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.searchqueueentry",
                    ),
                ),
            ],
            bases=("search.searchqueueentry",),
        ),
        migrations.CreateModel(
            name="TrackLineSearchQueueEntry",
            fields=[
                (
                    "searchqueueentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.searchqueueentry",
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="search.tracklinesearch",
                    ),
                ),
            ],
            bases=("search.searchqueueentry",),
        ),
        migrations.CreateModel(
            name="TrackLineCreepingSearchQueueEntry",
            fields=[
                (
                    "searchqueueentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.searchqueueentry",
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="search.tracklinecreepingsearch",
                    ),
                ),
            ],
            bases=("search.searchqueueentry",),
        ),
        migrations.CreateModel(
            name="SectorSearchQueueEntry",
            fields=[
                (
                    "searchqueueentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.searchqueueentry",
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="search.sectorsearch",
                    ),
                ),
            ],
            bases=("search.searchqueueentry",),
        ),
        migrations.AddIndex(
            model_name="searchqueueentry",
            index=models.Index(
                fields=["mission"], name="search_sear_mission_1e1048_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchqueueentry",
            index=models.Index(
                fields=["created_at"], name="search_sear_created_d63b3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchqueueentry",
            index=models.Index(
                fields=["deleted_at"], name="search_sear_deleted_61017a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchqueueentry",
            index=models.Index(fields=["asset"], name="search_sear_asset_i_bae2a9_idx"),
        ),
        migrations.AddIndex(
            model_name="searchqueueentry",
            index=models.Index(
                fields=["assettype"], name="search_sear_assetty_6ce6a4_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="expandingboxsearchqueueentry",
            name="searchqueueentry_ptr",
        ),
        migrations.RemoveField(
            model_name="polygonsearchqueueentry",
            name="searchqueueentry_ptr",
        ),
        migrations.RemoveField(
            model_name="searchqueueentry",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="searchqueueentry",
            name="assettype",
        ),
        migrations.RemoveField(
            model_name="searchqueueentry",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="searchqueueentry",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="searchqueueentry",
            name="mission",
        ),
        migrations.RemoveField(
            model_name="sectorsearchqueueentry",
            name="search",
        ),
        migrations.RemoveField(
            model_name="sectorsearchqueueentry",
            name="searchqueueentry_ptr",
        ),
        migrations.RemoveField(
            model_name="tracklinecreepingsearchqueueentry",
            name="search",
        ),
        migrations.RemoveField(
            model_name="tracklinecreepingsearchqueueentry",
            name="searchqueueentry_ptr",
        ),
        migrations.RemoveField(
            model_name="tracklinesearchqueueentry",
            name="search",
        ),
        migrations.RemoveField(
            model_name="tracklinesearchqueueentry",
            name="searchqueueentry_ptr",
        ),
        migrations.AddField(
            model_name="expandingboxsearch",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expandingboxsearch",
            name="queued_for_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queued_for_assettypesearch_expandingboxsearch_related",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="expandingboxsearch",
            name="queued_for_assettype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queued_for_assettypesearch_expandingboxsearch_related",
                to="assets.assettype",
            ),
        ),
        migrations.AddField(
            model_name="polygonsearch",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="polygonsearch",
            name="queued_for_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queued_for_assettypesearch_polygonsearch_related",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="polygonsearch",
            name="queued_for_assettype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queued_for_assettypesearch_polygonsearch_related",
                to="assets.assettype",
            ),
        ),
        migrations.AddField(
            model_name="sectorsearch",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sectorsearch",
            name="queued_for_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queued_for_assettypesearch_sectorsearch_related",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="sectorsearch",
            name="queued_for_assettype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queued_for_assettypesearch_sectorsearch_related",
                to="assets.assettype",
            ),
        ),
        migrations.AddField(
            model_name="tracklinecreepingsearch",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracklinecreepingsearch",
            name="queued_for_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queued_for_assettypesearch_tracklinecreepingsearch_related",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="tracklinecreepingsearch",
            name="queued_for_assettype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queued_for_assettypesearch_tracklinecreepingsearch_related",
                to="assets.assettype",
            ),
        ),
        migrations.AddField(
            model_name="tracklinesearch",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracklinesearch",
            name="queued_for_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queued_for_assettypesearch_tracklinesearch_related",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="tracklinesearch",
            name="queued_for_assettype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queued_for_assettypesearch_tracklinesearch_related",
                to="assets.assettype",
            ),
        ),
        migrations.AddIndex(
            model_name="expandingboxsearch",
            index=models.Index(
                fields=["deleted", "mission", "inprogress_by", "completed"],
                name="search_expa_deleted_61c18d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="polygonsearch",
            index=models.Index(
                fields=["deleted", "mission", "inprogress_by", "completed"],
                name="search_poly_deleted_7741f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sectorsearch",
            index=models.Index(
                fields=["deleted", "mission", "inprogress_by", "completed"],
                name="search_sect_deleted_93cc3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tracklinecreepingsearch",
            index=models.Index(
                fields=["deleted", "mission", "inprogress_by", "completed"],
                name="search_trac_deleted_fc74fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tracklinesearch",
            index=models.Index(
                fields=["deleted", "mission", "inprogress_by", "completed"],
                name="search_trac_deleted_302cee_idx",
            ),
        ),
        migrations.DeleteModel(
            name="ExpandingBoxSearchQueueEntry",
        ),
        migrations.DeleteModel(
            name="PolygonSearchQueueEntry",
        ),
        migrations.DeleteModel(
            name="SearchQueueEntry",
        ),
        migrations.DeleteModel(
            name="SectorSearchQueueEntry",
        ),
        migrations.DeleteModel(
            name="TrackLineCreepingSearchQueueEntry",
        ),
        migrations.DeleteModel(
            name="TrackLineSearchQueueEntry",
        ),
        migrations.RemoveIndex(
            model_name="expandingboxsearch",
            name="search_expa_deleted_61c18d_idx",
        ),
        migrations.RemoveIndex(
            model_name="polygonsearch",
            name="search_poly_deleted_7741f9_idx",
        ),
        migrations.RemoveIndex(
            model_name="sectorsearch",
            name="search_sect_deleted_93cc3d_idx",
        ),
        migrations.RemoveIndex(
            model_name="tracklinecreepingsearch",
            name="search_trac_deleted_fc74fa_idx",
        ),
        migrations.RemoveIndex(
            model_name="tracklinesearch",
            name="search_trac_deleted_302cee_idx",
        ),
        migrations.RenameField(
            model_name="sectorsearch",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="sectorsearch",
            old_name="line",
            new_name="geo",
        ),
        migrations.RenameField(
            model_name="sectorsearch",
            old_name="creator",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="sectorsearch",
            old_name="datum",
            new_name="old_datum",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX search_sectorsearch_datum_id_dda41ace RENAME TO search_sectorsearch_old_datum_id_dda41ace",
        ),
        migrations.AddField(
            model_name="sectorsearch",
            name="replaced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sectorsearch",
            name="geo",
            field=django.contrib.gis.db.models.fields.GeometryField(
                geography=True, srid=4326
            ),
        ),
        migrations.RemoveField(
            model_name="sectorsearch",
            name="deleted",
        ),
        migrations.AlterField(
            model_name="sectorsearch",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_bysearch_sectorsearch_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="expandingboxsearch",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="expandingboxsearch",
            old_name="line",
            new_name="geo",
        ),
        migrations.RenameField(
            model_name="expandingboxsearch",
            old_name="creator",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="expandingboxsearch",
            old_name="datum",
            new_name="old_datum",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX search_expandingboxsearch_datum_id_81e8068a RENAME TO search_expandingboxsearch_old_datum_id_81e8068a",
        ),
        migrations.AddField(
            model_name="expandingboxsearch",
            name="replaced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expandingboxsearch",
            name="geo",
            field=django.contrib.gis.db.models.fields.GeometryField(
                geography=True, srid=4326
            ),
        ),
        migrations.RemoveField(
            model_name="expandingboxsearch",
            name="deleted",
        ),
        migrations.AlterField(
            model_name="expandingboxsearch",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_bysearch_expandingboxsearch_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="tracklinesearch",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="tracklinesearch",
            old_name="line",
            new_name="geo",
        ),
        migrations.RenameField(
            model_name="tracklinesearch",
            old_name="creator",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="tracklinesearch",
            old_name="datum",
            new_name="old_datum",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX search_tracklinesearch_datum_id_6f9daedc RENAME TO search_tracklinesearch_old_datum_id_6f9daedc",
        ),
        migrations.AddField(
            model_name="tracklinesearch",
            name="replaced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracklinesearch",
            name="geo",
            field=django.contrib.gis.db.models.fields.GeometryField(
                geography=True, srid=4326
            ),
        ),
        migrations.RemoveField(
            model_name="tracklinesearch",
            name="deleted",
        ),
        migrations.AlterField(
            model_name="tracklinesearch",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_bysearch_tracklinesearch_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="tracklinecreepingsearch",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="tracklinecreepingsearch",
            old_name="line",
            new_name="geo",
        ),
        migrations.RenameField(
            model_name="tracklinecreepingsearch",
            old_name="creator",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="tracklinecreepingsearch",
            old_name="datum",
            new_name="old_datum",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX search_tracklinecreepingsearch_datum_id_4c5ab4f4 RENAME TO search_tracklinecreepingsearch_old_datum_id_4c5ab4f4",
        ),
        migrations.AddField(
            model_name="tracklinecreepingsearch",
            name="replaced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracklinecreepingsearch",
            name="geo",
            field=django.contrib.gis.db.models.fields.GeometryField(
                geography=True, srid=4326
            ),
        ),
        migrations.RemoveField(
            model_name="tracklinecreepingsearch",
            name="deleted",
        ),
        migrations.AlterField(
            model_name="tracklinecreepingsearch",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_bysearch_tracklinecreepingsearch_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="polygonsearch",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="polygonsearch",
            old_name="line",
            new_name="geo",
        ),
        migrations.RenameField(
            model_name="polygonsearch",
            old_name="creator",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="polygonsearch",
            old_name="datum",
            new_name="old_datum",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX search_polygonsearch_datum_id_100fbeff RENAME TO search_polygonsearch_old_datum_id_100fbeff",
        ),
        migrations.AddField(
            model_name="polygonsearch",
            name="replaced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="polygonsearch",
            name="geo",
            field=django.contrib.gis.db.models.fields.GeometryField(
                geography=True, srid=4326
            ),
        ),
        migrations.RemoveField(
            model_name="polygonsearch",
            name="deleted",
        ),
        migrations.AlterField(
            model_name="polygonsearch",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_bysearch_polygonsearch_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expandingboxsearch",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expandingboxsearch",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deletorsearch_expandingboxsearch_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="polygonsearch",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="polygonsearch",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deletorsearch_polygonsearch_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sectorsearch",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sectorsearch",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deletorsearch_sectorsearch_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tracklinecreepingsearch",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracklinecreepingsearch",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deletorsearch_tracklinecreepingsearch_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tracklinesearch",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracklinesearch",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deletorsearch_tracklinesearch_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expandingboxsearch",
            name="alt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="polygonsearch",
            name="alt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sectorsearch",
            name="alt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracklinecreepingsearch",
            name="alt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracklinesearch",
            name="alt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sectorsearch",
            name="datum",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="data.geotimelabel",
            ),
        ),
        migrations.AddField(
            model_name="expandingboxsearch",
            name="datum",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="data.geotimelabel",
            ),
        ),
        migrations.AddField(
            model_name="tracklinesearch",
            name="datum",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="data.geotimelabel",
            ),
        ),
        migrations.AddField(
            model_name="tracklinecreepingsearch",
            name="datum",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="data.geotimelabel",
            ),
        ),
        migrations.AddField(
            model_name="polygonsearch",
            name="datum",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="data.geotimelabel",
            ),
        ),
    ]
