name: ESLint

on:
  pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Install modules
       run: npm ci
     - name: Run ESLint
       run: npm run check
