name: Run Tests

on:
  pull_request:
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgis/postgis:18-3.6-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v7
      - name: Update apt database
        run: sudo apt update
      - name: Install apt depends
        run: sudo apt install -y gdal-bin libgdal-dev
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Setup venv
        run: ./setup-venv.sh
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASS: postgres
          DB_NAME: postgres
      - name: Run Tests
        run: ./test-venv.sh
